# docker-compose.yml  (principal)
services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - monitoring-net

  calculadora:
    image: ghcr.io/brillaldo/calculadora-backend:latest
    pull_policy: always
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      monitoring-net:
        aliases:
          - backend   # 👈 para que Prometheus "vea" backend:8000

  frontend:
    image: ghcr.io/brillaldo/calculadora-frontend:latest
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - calculadora
    ports:
      - "3000:3000"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    name: monitoring-net  # 👈 mismo nombre que usarás en /monitoring
