name: Frontend - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yaml"
    tags:
      - "v*"
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image meta
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_LOWER" >> $GITHUB_ENV
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}-frontend:${{ env.TAG }} ./frontend

      - name: Push
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}-frontend:${{ env.TAG }}
